---
- name: Install Keystone (Identity Service) on Controller (Ubuntu)
  hosts: controller
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Keystone packages
      apt:
        name:
          - keystone
          - apache2
          - libapache2-mod-wsgi
        state: present

    - name: Configure Keystone database
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" -e "
        CREATE DATABASE keystone;
        GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ keystone_db_password }}';
        GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ keystone_db_password }}';
        FLUSH PRIVILEGES;"

    - name: Populate the Keystone database
      shell: |
        keystone-manage db_sync

    - name: Initialize Fernet keys for Keystone
      shell: |
        keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
        keystone-manage credential_setup --keystone-user keystone --keystone-group keystone

    - name: Bootstrap Keystone
      shell: |
        keystone-manage bootstrap --bootstrap-password {{ keystone_admin_password }} \
          --bootstrap-admin-url http://{{ controller_ip }}:5000/v3/ \
          --bootstrap-internal-url http://{{ controller_ip }}:5000/v3/ \
          --bootstrap-public-url http://{{ controller_ip }}:5000/v3/ \
          --bootstrap-region-id RegionOne

- name: Install Glance (Image Service) on Controller (Ubuntu)
  hosts: controller
  become: true
  tasks:
    - name: Install Glance packages
      apt:
        name:
          - glance
        state: present

    - name: Configure Glance database
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" -e "
        CREATE DATABASE glance;
        GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '{{ glance_db_password }}';
        GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '{{ glance_db_password }}';
        FLUSH PRIVILEGES;"

    - name: Populate the Glance database
      shell: |
        glance-manage db_sync

    - name: Start and enable Glance services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - glance-api
        - glance-registry

- name: Install Nova (Compute Service) on Compute Node (CentOS)
  hosts: compute
  become: true
  tasks:
    - name: Install Nova Compute packages
      dnf:
        name:
          - openstack-nova-compute
        state: present

    - name: Configure Nova Compute
      lineinfile:
        path: /etc/nova/nova.conf
        regexp: "^{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "^my_ip", line: "my_ip = {{ ansible_host }}" }
        - { regexp: "^auth_strategy", line: "auth_strategy = keystone" }

    - name: Start and enable Nova Compute service
      systemd:
        name: openstack-nova-compute
        state: started
        enabled: true

fatal: [192.168.56.105]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.56.105 closed.\r\n", "module_stdout": "\r\nErrors during downloading metadata for repository 'baseos':\r\n  - Status code: 404 for https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=x86_64&protocol=https,http (IP: 54.180.100.16)\r\n  - Status code: 404 for https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=x86_64&protocol=https,http (IP: 18.136.235.60)\r\nTraceback (most recent call last):\r\n  File \"/usr/lib/python3.9/site-packages/dnf/repo.py\", line 574, in load\r\n    ret = self._repo.load()\r\n  File \"/usr/lib64/python3.9/site-packages/libdnf/repo.py\", line 331, in load\r\n    return _repo.Repo_load(self)\r\nlibdnf._error.Error: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=x86_64&protocol=https,http (IP: 18.136.235.60)\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_17vij4tq/ansible_module_dnf.py\", line 534, in <module>\r\n    main()\r\n  File \"/tmp/ansible_17vij4tq/ansible_module_dnf.py\", line 526, in main\r\n    base = _base(\r\n  File \"/tmp/ansible_17vij4tq/ansible_module_dnf.py\", line 251, in _base\r\n    base.fill_sack(load_system_repo='auto')\r\n  File \"/usr/lib/python3.9/site-packages/dnf/base.py\", line 406, in fill_sack\r\n    self._add_repo_to_sack(r)\r\n  File \"/usr/lib/python3.9/site-packages/dnf/base.py\", line 141, in _add_repo_to_sack\r\n    repo.load()\r\n  File \"/usr/lib/python3.9/site-packages/dnf/repo.py\", line 581, in load\r\n    raise dnf.exceptions.RepoError(str(e))\r\ndnf.exceptions.RepoError: Failed to download metadata for repo 'baseos': Cannot prepare internal mirrorlist: Status code: 404 for https://mirrors.centos.org/metalink?repo=centos-baseos-$stream&arch=x86_64&protocol=https,http (IP: 18.136.235.60)\r\n", "msg": "MODULE FAILURE", "rc": 1}

